-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  base_salary numeric default 15000,
  work_days_per_month int default 30,
  work_hours_per_day int default 8,
  work_start_time text default '08:00',
  work_end_time text default '17:00',
  meow_points int default 0,
  pet_exp int default 0,
  pet_level int default 1,
  
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(full_name) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for OT Records
create table ot_records (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  hours numeric not null,
  rate_multiplier numeric default 1.5, -- 1.5, 2.0, 3.0
  total_income numeric not null,
  
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table ot_records enable row level security;

create policy "Users can view own OT records." on ot_records
  for select using (auth.uid() = user_id);

create policy "Users can insert own OT records." on ot_records
  for insert with check (auth.uid() = user_id);

create policy "Users can update own OT records." on ot_records
  for update using (auth.uid() = user_id);

create policy "Users can delete own OT records." on ot_records
  for delete using (auth.uid() = user_id);

-- AUTOMATIC PROFILE CREATION TRIGGER
-- This ensures that when a user signs up via Auth, a public profile row is created automatically.

-- 1. Create the function
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, meow_points, pet_exp, pet_level)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    0,
    0,
    1
  );
  return new;
end;
$$;

-- 2. Create the trigger
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
